
SOURCES		= afm.scm \
		  afmdef.scm \
		  baghdad.scm \
		  bindings.scm \
		  charset.scm \
		  column.scm \
		  content.scm \
		  decomp.scm \
		  device.scm \
		  font.scm \
		  formatter.scm \
		  glyph.scm \
		  graphprim.scm \
		  hbb.scm \
		  line.scm \
		  lineview.scm \
		  macros.scm \
		  misc.scm \
		  mitmacros.scm \
		  nsm.scm \
		  page.scm \
		  postscript.scm \
		  ramatgan.scm \
		  render.scm \
		  rtf.scm \
		  stream.scm \
		  style.scm \
		  templates.scm \
		  text.scm \
		  truetype.scm \
		  utf.scm \
		  viewer.scm

BINARIES	= afm.com \
		  afmdef.com \
		  baghdad.com \
		  bindings.com \
		  charset.com \
		  column.com \
		  content.com \
		  decomp.com \
		  device.com \
		  font.com \
		  formatter.com \
		  glyph.com \
		  graphprim.com \
		  hbb.com \
		  line.com \
		  lineview.com \
		  macros.com \
		  misc.com \
		  mitmacros.com \
		  nsm.com \
		  page.com \
		  postscript.com \
		  ramatgan.com \
		  render.com \
		  rtf.com \
		  stream.com \
		  style.com \
		  templates.com \
		  text.com \
		  truetype.com \
		  utf.com \
		  viewer.com

all: ${BINARIES}

afm.com: afm.scm
	@echo Build afm.scm

afmdef.com: afmdef.scm
	@echo Build afmdef.scm

baghdad.com: baghdad.scm
	@echo Build baghdad.scm

bindings.com: bindings.scm
	@echo Build bindings.scm

charset.com: charset.scm
	@echo Build charset.scm

column.com: column.scm
	@echo Build column.scm

content.com: content.scm
	@echo Build content.scm

decomp.com: decomp.scm
	@echo Build decomp.scm

device.com: device.scm
	@echo Build device.scm

font.com: font.scm
	@echo Build font.scm

formatter.com: formatter.scm
	@echo Build formatter.scm

glyph.com: glyph.scm
	@echo Build glyph.scm

graphprim.com: graphprim.scm
	@echo Build graphprim.scm

hbb.com: hbb.scm
	@echo Build hbb.scm

line.com: line.scm
	@echo Build line.scm

lineview.com: lineview.scm
	@echo Build lineview.scm

macros.com: macros.scm
	@echo Build macros.scm

misc.com: misc.scm
	@echo Build misc.scm

mitmacros.com: mitmacros.scm
	@echo Build mitmacros.scm

nsm.com: nsm.scm
	@echo Build nsm.scm

page.com: page.scm
	@echo Build page.scm

postscript.com: postscript.scm
	@echo Build postscript.scm

ramatgan.com: ramatgan.scm
	@echo Build ramatgan.scm

render.com: render.scm
	@echo Build render.scm

rtf.com: rtf.scm
	@echo Build rtf.scm

stream.com: stream.scm
	@echo Build stream.scm

style.com: style.scm
	@echo Build style.scm

templates.com: templates.scm
	@echo Build templates.scm

text.com: text.scm
	@echo Build text.scm

truetype.com: truetype.scm
	@echo Build truetype.scm

utf.com: utf.scm
	@echo Build utf.scm

viewer.com: viewer.scm
	@echo Build viewer.scm
